[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.13"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
