[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
anyhow = "1.0"