port = 3000
debug = false
log_level = "info"

[database]
url = "postgres://localhost/myapp"
pool_size = 10
timeout = 30

[server]
host = "127.0.0.1"
port = 8080
workers = 4

[redis]
url = "redis://localhost/"
pool_size = 6