[package]
name = "http-request"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
reqwest = "0.12.22"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
