[server]
host = "127.0.0.1"
port = 3000
timeout_seconds = 30

[cors]
origins = ["http://localhost:3000", "http://localhost:3001"]
max_age_seconds = 3600

[log]
level = "debug"
format = "pretty"

[counter]
max_value = 1000000
initial_value = 0